# Generated by Django 3.2.18 on 2023-12-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minhaeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
