# Generated by Django 3.2.18 on 2023-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minhaeiro', '0002_auto_20231228_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expenses',
            field=models.FloatField(default=0),
        ),
    ]
