# Generated by Django 3.2.18 on 2023-12-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_minhaeiro', '0007_alter_creditcard_pay_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Adicionar', 'Positivo'), ('Retirar', 'Negativo')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='parcelado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
